
global:
  scrape_interval:     15s
scrape_configs:
  - job_name: 'image-builder'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8086']
  - job_name: 'composer'
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true
      cert_file: /etc/image-builder/client-crt.pem
      key_file: /etc/image-builder/client-key.pem
    static_configs:
      - targets: ['composer:8080']
