[authentication]
oauth_url = "http://fauxauth:8888/token?refresh_token=42"
client_secret = "/etc/osbuild-worker/secret"
client_id = "rhsm-api"

[generic_s3]
credentials = "/etc/osbuild-worker/s3-credentials"
region = "us-east-1"
bucket = "service"
endpoint = "http://minio:9000"
skip_ssl_verification = true
